### ISSUE TITLE
Out of Memory Error When Building Index

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/Usagi#59]
Hello,

**Where should I set the java heap space parameter and to what number specifically when building the index?**

When trying to build the index with the latest vocabularies and the latest version of Usagi, it gets stuck at : 
_Building index.  This will take awhile....
Adding concepts to search index._

The ErrorStream shows an OutofMemoryError.  

```
 Exception in thread "Thread-3" java.lang.OutOfMemoryError: Java heap space
	at org.apache.lucene.util.ByteBlockPool$DirectTrackingAllocator.getByteBlock(ByteBlockPool.java:103)
	at org.apache.lucene.util.ByteBlockPool.nextBuffer(ByteBlockPool.java:202)
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:115)
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:189)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:645)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:342)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:301)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:222)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1507)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1222)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1203)
	at org.ohdsi.usagi.UsagiSearchEngine.addTermToIndex(Unknown Source)
	at org.ohdsi.usagi.indexBuilding.LuceneIndexBuilder.buildIndex(Unknown Source)
	at org.ohdsi.usagi.indexBuilding.IndexBuildCoordinator$BuildThread.run(Unknown Source)
```

**Comment by schuemie** [comment]
You can try starting Usagi from the command prompt:
```
java -Xmx2000m -jar Usagi_v1.2.7.jar
```
where -Xmx2000m sets the heap size to 2000 MB. The default is 1000m, so twice as much would be a good place to start. It of course depends on how much memory you have available.

Could you prove the list of vocabularies you're including in your Athena download, so I can try to replicate this problem?

**Comment by anonymous34** [comment]
I was able to get it work with running the command above with a heap size of 1500MB.  Using 2000MB caused a could not reserve enough space for object heap error.  However, while I was able to build the index, I can only open the jar file through the command line.  Opening the jar file by itself causes this error:

```
Exception in thread "main" java.lang.RuntimeException: com.sleepycat.je.EnvironmentFailureException: (JE 7.3.7) C:\Usagi-1.2.7\Usagi-1.2.7\sleepyCat java.io.FileNotFoundException: C:\Usagi-1.2.7\Usagi-1.2.7\sleepyCat\je.lck (Access is denied) LOG_INTEGRITY: Log information is incorrect, problem is likely persistent. Environment is invalid and must be closed.
	at org.ohdsi.usagi.BerkeleyDbEngine.open(Unknown Source)
	at org.ohdsi.usagi.BerkeleyDbEngine.openForReading(Unknown Source)
	at org.ohdsi.usagi.ui.UsagiMain.<init>(Unknown Source)
	at org.ohdsi.usagi.ui.UsagiMain.main(Unknown Source)
Caused by: com.sleepycat.je.EnvironmentFailureException: (JE 7.3.7) C:\Usagi-1.2.7\Usagi-1.2.7\sleepyCat java.io.FileNotFoundException: C:\Usagi-1.2.7\Usagi-1.2.7\sleepyCat\je.lck (Access is denied) LOG_INTEGRITY: Log information is incorrect, problem is likely persistent. Environment is invalid and must be closed.
	at com.sleepycat.je.log.FileManager.lockEnvironment(FileManager.java:2245)
	at com.sleepycat.je.log.FileManager.<init>(FileManager.java:377)
	at com.sleepycat.je.dbi.EnvironmentImpl.<init>(EnvironmentImpl.java:601)
	at com.sleepycat.je.dbi.EnvironmentImpl.<init>(EnvironmentImpl.java:487)
	at com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:192)
	at com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:267)
	at com.sleepycat.je.Environment.<init>(Environment.java:252)
	at com.sleepycat.je.Environment.<init>(Environment.java:222)
	... 4 more
Caused by: java.io.FileNotFoundException: C:\Usagi-1.2.7\Usagi-1.2.7\sleepyCat\je.lck (Access is denied)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at com.sleepycat.je.log.FileManager.lockEnvironment(FileManager.java:2214)
	... 11 more

```

The list of vocabularies are 
![image](https://user-images.githubusercontent.com/33704272/57473447-74ddf280-7255-11e9-85f1-0f7a20df925f.png)

**Comment by schuemie** [comment]
Not sure this will help, but you'll be able to allocate more memory if you install a 64-bit version of Java.

I'm trying to reproduce the problem now.

**Comment by schuemie** [comment]
I can reproduce the problem, and just [changing this number](https://github.com/OHDSI/Usagi/commit/98e086415ca00cdc1b63380bb15772e9dabc15b2) solves the problem in my environment.

Could you try [this new version](https://github.com/OHDSI/Usagi/releases/tag/v1.2.8) to see if it works for you too?

**Comment by anonymous34** [comment]
Thanks I will try.  Another question though.  If you need to come back to the mapping document later and close Usagi because the machine is being rebooted, would you just import the source to concept map you previously exported?  We tried doing that, but the file is not opening.  It says it is open, but nothing shows up in Usagi. 

The error log says this:

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Field "sourceCode" not found
                at org.ohdsi.utilities.files.Row.get(Unknown Source)
                at org.ohdsi.usagi.SourceCode.<init>(Unknown Source)
                at org.ohdsi.usagi.ReadCodeMappingsFromFile$RowIterator.readNext(Unknown Source)
                at org.ohdsi.usagi.ReadCodeMappingsFromFile$RowIterator.<init>(Unknown Source)
                at org.ohdsi.usagi.ReadCodeMappingsFromFile.iterator(Unknown Source)
                at org.ohdsi.usagi.ui.Mapping.loadFromFile(Unknown Source)
                at org.ohdsi.usagi.ui.actions.OpenAction.actionPerformed(Unknown Source)
                at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
                at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
                at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
                at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
                at javax.swing.AbstractButton.doClick(Unknown Source)
                at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
                at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
                at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
                at java.awt.Component.processMouseEvent(Unknown Source)
                at javax.swing.JComponent.processMouseEvent(Unknown Source)
                at java.awt.Component.processEvent(Unknown Source)
                at java.awt.Container.processEvent(Unknown Source)
                at java.awt.Component.dispatchEventImpl(Unknown Source)
                at java.awt.Container.dispatchEventImpl(Unknown Source)
                at java.awt.Component.dispatchEvent(Unknown Source)
                at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
                at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
                at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
                at java.awt.Container.dispatchEventImpl(Unknown Source)
                at java.awt.Window.dispatchEventImpl(Unknown Source)
                at java.awt.Component.dispatchEvent(Unknown Source)
                at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
                at java.awt.EventQueue.access$500(Unknown Source)
                at java.awt.EventQueue$3.run(Unknown Source)
                at java.awt.EventQueue$3.run(Unknown Source)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
                at java.awt.EventQueue$4.run(Unknown Source)
                at java.awt.EventQueue$4.run(Unknown Source)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
                at java.awt.EventQueue.dispatchEvent(Unknown Source)
                at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
                at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
                at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
                at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
                at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
                at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Field "sourceCode" not found
                at org.ohdsi.utilities.files.Row.get(Unknown Source)
                at org.ohdsi.usagi.SourceCode.<init>(Unknown Source)
                at org.ohdsi.usagi.ReadCodeMappingsFromFile$RowIterator.readNext(Unknown Source)
                at org.ohdsi.usagi.ReadCodeMappingsFromFile$RowIterator.<init>(Unknown Source)
                at org.ohdsi.usagi.ReadCodeMappingsFromFile.iterator(Unknown Source)
                at org.ohdsi.usagi.ui.Mapping.loadFromFile(Unknown Source)
                at org.ohdsi.usagi.ui.actions.OpenAction.actionPerformed(Unknown Source)
                at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
                at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
                at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
                at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
                at javax.swing.AbstractButton.doClick(Unknown Source)
                at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
                at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
                at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
                at java.awt.Component.processMouseEvent(Unknown Source)
                at javax.swing.JComponent.processMouseEvent(Unknown Source)
                at java.awt.Component.processEvent(Unknown Source)
                at java.awt.Container.processEvent(Unknown Source)
                at java.awt.Component.dispatchEventImpl(Unknown Source)
                at java.awt.Container.dispatchEventImpl(Unknown Source)
                at java.awt.Component.dispatchEvent(Unknown Source)
                at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
                at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
                at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
                at java.awt.Container.dispatchEventImpl(Unknown Source)
                at java.awt.Window.dispatchEventImpl(Unknown Source)
                at java.awt.Component.dispatchEvent(Unknown Source)
                at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
                at java.awt.EventQueue.access$500(Unknown Source)
                at java.awt.EventQueue$3.run(Unknown Source)
                at java.awt.EventQueue$3.run(Unknown Source)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
                at java.awt.EventQueue$4.run(Unknown Source)
                at java.awt.EventQueue$4.run(Unknown Source)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
                at java.awt.EventQueue.dispatchEvent(Unknown Source)
                at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
                at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
                at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
                at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
                at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
                at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by schuemie** [comment]
There are the 'Save', 'Save as', and 'Open' options in the 'File' menu for saving and loading mappings. 

Importing a previously exported source_to_concept_map is not that easy.
