### ISSUE TITLE
Cannot complete initial index building

### ISSUE THREAD

**Issue by otaka0721** [OHDSI/Usagi#63]
In order to start using Usagi, I designated the directory of the vocabulary file (local) and tried to build index. However, building initial index did not complete after running overnight. The window continued showing message 'Adding concept to search index'. In the vocabulary folder, sleepyCat and mainIndex folder were created, but I'm not sure they are completely generated. In the ErrorStream, following texts were contained. What could be the cause for this situation?

[ErrorStream file]
Exception in thread "Thread-3" java.lang.OutOfMemoryError: Java heap space
	at org.apache.lucene.util.ByteBlockPool$DirectTrackingAllocator.getByteBlock(ByteBlockPool.java:103)
	at org.apache.lucene.util.ByteBlockPool.nextBuffer(ByteBlockPool.java:202)
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:115)
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:189)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:645)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:342)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:301)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:222)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1507)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1222)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1203)
	at org.ohdsi.usagi.UsagiSearchEngine.addTermToIndex(Unknown Source)
	at org.ohdsi.usagi.indexBuilding.LuceneIndexBuilder.buildIndex(Unknown Source)
	at org.ohdsi.usagi.indexBuilding.IndexBuildCoordinator$BuildThread.run(Unknown Source)

**Comment by MaximMoinat** [comment]
Java has run out of memory. You can allocate more memory by starting Usagi with the -Xmx flag: for example `java -Xmx2048m` to allocate 2gb of memory.
